/**
 * Códigos de error propios de BE05. Igual que en BE04, viven en el módulo para
 * no tocar el enum compartido; consolidarlos es decisión del coordinador.
 */
export const TemplateErrorCodes = {
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_VERSION_NOT_FOUND: 'TEMPLATE_VERSION_NOT_FOUND',
  TEMPLATE_VERSION_CONFLICT: 'TEMPLATE_VERSION_CONFLICT',
  TEMPLATE_ZPL_INVALID: 'TEMPLATE_ZPL_INVALID',
  TEMPLATE_FIELDS_INVALID: 'TEMPLATE_FIELDS_INVALID',
  TEMPLATE_LIMIT_EXCEEDED: 'TEMPLATE_LIMIT_EXCEEDED',
  TEMPLATE_VERSION_LIMIT_EXCEEDED: 'TEMPLATE_VERSION_LIMIT_EXCEEDED',
  TEMPLATE_ARCHIVED: 'TEMPLATE_ARCHIVED',
  /** La cuenta está marcada como borrada: no admite escrituras nuevas. */
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  TEMPLATE_ROW_ERRORS: 'TEMPLATE_ROW_ERRORS',
  TEMPLATE_RUN_NOT_FOUND: 'TEMPLATE_RUN_NOT_FOUND',
  TEMPLATE_RUN_EMPTY: 'TEMPLATE_RUN_EMPTY',
  TEMPLATE_LABEL_LIMIT_EXCEEDED: 'TEMPLATE_LABEL_LIMIT_EXCEEDED',
  MAPPING_INVALID: 'MAPPING_INVALID',
  COLUMN_MISSING: 'COLUMN_MISSING',
  AMBIGUOUS_DELIMITER: 'AMBIGUOUS_DELIMITER',
  DATA_TOO_LARGE: 'DATA_TOO_LARGE',
  DATA_EMPTY: 'DATA_EMPTY',
  DATA_INVALID: 'DATA_INVALID',
  XLSX_MACROS_NOT_ALLOWED: 'XLSX_MACROS_NOT_ALLOWED',
  XLSX_SHEET_NOT_FOUND: 'XLSX_SHEET_NOT_FOUND',
  FEATURE_UNSUPPORTED: 'FEATURE_UNSUPPORTED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  RUN_IN_PROGRESS: 'RUN_IN_PROGRESS',
} as const;

/** Diagnóstico por fila. Se devuelve en `data.rows`, nunca como un error suelto. */
export const RowErrorCodes = {
  ROW_EMPTY: 'ROW_EMPTY',
  ROW_REQUIRED_MISSING: 'ROW_REQUIRED_MISSING',
  ROW_TOO_LONG: 'ROW_TOO_LONG',
  ROW_CHARSET: 'ROW_CHARSET',
  ROW_CONTROL_CHAR: 'ROW_CONTROL_CHAR',
  ROW_INVALID_INTEGER: 'ROW_INVALID_INTEGER',
  ROW_INVALID_DECIMAL: 'ROW_INVALID_DECIMAL',
  ROW_AMBIGUOUS_NUMBER: 'ROW_AMBIGUOUS_NUMBER',
  ROW_AMBIGUOUS_LEADING_ZERO: 'ROW_AMBIGUOUS_LEADING_ZERO',
  ROW_INVALID_DATE: 'ROW_INVALID_DATE',
  ROW_INVALID_QUANTITY: 'ROW_INVALID_QUANTITY',
  ROW_FORMULA_NOT_ALLOWED: 'ROW_FORMULA_NOT_ALLOWED',
  ROW_CELL_ERROR: 'ROW_CELL_ERROR',
  ROW_CELL_TOO_LARGE: 'ROW_CELL_TOO_LARGE',
  ROW_COLUMN_MISSING: 'ROW_COLUMN_MISSING',
} as const;
