/**
 * Códigos de error propios de BE04.
 *
 * Viven aquí y no en `src/common/constants/error-codes.ts` porque ese archivo es
 * compartido y este cambio no toca archivos fuera de sus módulos. Consolidarlos
 * allí es una decisión del coordinador (ver contrato, §6). Los códigos que ya
 * existen en el enum global (INVALID_ZPL, ACCESS_DENIED, …) se reutilizan tal
 * cual desde ese archivo.
 */
export const WorkflowErrorCodes = {
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_VERSION_CONFLICT: 'WORKFLOW_VERSION_CONFLICT',
  WORKFLOW_ORDER_MISMATCH: 'WORKFLOW_ORDER_MISMATCH',
  WORKFLOW_SELECTION_EMPTY: 'WORKFLOW_SELECTION_EMPTY',
  WORKFLOW_LABEL_LIMIT_EXCEEDED: 'WORKFLOW_LABEL_LIMIT_EXCEEDED',
  WORKFLOW_COPIES_LIMIT_EXCEEDED: 'WORKFLOW_COPIES_LIMIT_EXCEEDED',
  /** La etiqueta usa ^SN/^SF: cambiar sus copias alteraría la serie impresa. */
  WORKFLOW_SERIALIZED_LABEL: 'WORKFLOW_SERIALIZED_LABEL',
  WORKFLOW_SOURCE_TOO_LARGE: 'WORKFLOW_SOURCE_TOO_LARGE',
  WORKFLOW_SOURCE_EXPIRED: 'WORKFLOW_SOURCE_EXPIRED',
  WORKFLOW_QUOTA_EXCEEDED: 'WORKFLOW_QUOTA_EXCEEDED',
  WORKFLOW_ARCHIVED: 'WORKFLOW_ARCHIVED',
  /** La cuenta está marcada como borrada: no admite escrituras nuevas. */
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  EXPORT_NOT_FOUND: 'EXPORT_NOT_FOUND',
  EXPORT_IN_PROGRESS: 'EXPORT_IN_PROGRESS',
  EXPORT_LIMIT_EXCEEDED: 'EXPORT_LIMIT_EXCEEDED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  RECONCILE_HEADER_MISMATCH: 'RECONCILE_HEADER_MISMATCH',
  RECONCILE_AMBIGUOUS_DELIMITER: 'RECONCILE_AMBIGUOUS_DELIMITER',
  RECONCILE_EMPTY: 'RECONCILE_EMPTY',
  RECONCILE_TOO_LARGE: 'RECONCILE_TOO_LARGE',
  RECONCILE_ROW_ERRORS: 'RECONCILE_ROW_ERRORS',
} as const;

export type WorkflowErrorCode =
  (typeof WorkflowErrorCodes)[keyof typeof WorkflowErrorCodes];
