import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  IsArray,
  IsNotEmpty,
  ValidateNested,
  ArrayMinSize,
  IsEnum,
  IsOptional,
} from 'class-validator';
import { Type } from 'class-transformer';

// Input DTOs
export class BatchFileDto {
  @ApiProperty({ description: 'UUID generated by frontend' })
  @IsString()
  @IsNotEmpty()
  id: string;

  @ApiProperty({ description: 'ZPL content' })
  @IsString()
  @IsNotEmpty()
  content: string;

  @ApiProperty({ description: 'Original file name' })
  @IsString()
  @IsNotEmpty()
  fileName: string;
}

export class BatchConvertDto {
  @ApiProperty({
    type: [BatchFileDto],
    description: 'Array of ZPL files to convert',
  })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => BatchFileDto)
  files: BatchFileDto[];

  // NOTA: este DTO documenta la forma del endpoint en Swagger, pero
  // `POST /zpl/batch` no lo usa como `@Body()` (recibe multipart/form-data vía
  // `@UploadedFiles()` + un tipo ad-hoc en el controller, no esta clase), así
  // que `class-validator` nunca corre sobre este campo. La validación real de
  // labelSize (incluida contra valores no reconocidos, issue #101) vive en
  // `ZplService.startBatchConversion`, que sigue aceptando string libre a
  // propósito: el batch históricamente guarda el tamaño sin normalizar
  // (`large`, `small`, …) en conversion_history.
  @ApiProperty({ description: 'Label size (e.g., 4x6, 50x80mm)' })
  @IsString()
  @IsNotEmpty()
  labelSize: string;

  @ApiPropertyOptional({ enum: ['pdf', 'png', 'jpeg'], default: 'pdf' })
  @IsOptional()
  @IsEnum(['pdf', 'png', 'jpeg'])
  outputFormat?: 'pdf' | 'png' | 'jpeg';
}

// Response DTOs
export class BatchJobMappingDto {
  @ApiProperty()
  fileId: string;

  @ApiProperty()
  jobId: string;
}

export class BatchConvertResponseDto {
  @ApiProperty()
  batchId: string;

  @ApiProperty({ type: [BatchJobMappingDto] })
  jobs: BatchJobMappingDto[];
}

export class BatchFileStatusDto {
  @ApiProperty()
  jobId: string;

  @ApiProperty({ enum: ['pending', 'processing', 'completed', 'failed'] })
  status: string;

  @ApiProperty()
  progress: number;

  @ApiPropertyOptional()
  error?: string;
}

export class BatchStatusResponseDto {
  @ApiProperty()
  batchId: string;

  @ApiProperty({ enum: ['processing', 'completed', 'partial', 'failed'] })
  status: string;

  @ApiProperty()
  totalFiles: number;

  @ApiProperty()
  completedFiles: number;

  @ApiProperty({ type: [BatchFileStatusDto] })
  jobs: BatchFileStatusDto[];

  @ApiPropertyOptional()
  downloadUrl?: string;
}

export class BatchDownloadResponseDto {
  @ApiProperty()
  url: string;

  @ApiProperty()
  filename: string;

  @ApiProperty()
  expiresAt: string;
}

// Error DTOs
export class BatchErrorDto {
  @ApiProperty()
  error: string;

  @ApiProperty()
  message: string;
}
