import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  IsArray,
  IsNotEmpty,
  ValidateNested,
  ArrayMinSize,
  IsEnum,
  IsOptional,
} from 'class-validator';
import { Type } from 'class-transformer';

// Input DTOs
export class BatchFileDto {
  @ApiProperty({ description: 'UUID generated by frontend' })
  @IsString()
  @IsNotEmpty()
  id: string;

  @ApiProperty({ description: 'ZPL content' })
  @IsString()
  @IsNotEmpty()
  content: string;

  @ApiProperty({ description: 'Original file name' })
  @IsString()
  @IsNotEmpty()
  fileName: string;
}

export class BatchConvertDto {
  @ApiProperty({ type: [BatchFileDto], description: 'Array of ZPL files to convert' })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => BatchFileDto)
  files: BatchFileDto[];

  @ApiProperty({ description: 'Label size (e.g., 4x6, 4x4)' })
  @IsString()
  @IsNotEmpty()
  labelSize: string;

  @ApiPropertyOptional({ enum: ['pdf', 'png', 'jpeg'], default: 'pdf' })
  @IsOptional()
  @IsEnum(['pdf', 'png', 'jpeg'])
  outputFormat?: 'pdf' | 'png' | 'jpeg';
}

// Response DTOs
export class BatchJobMappingDto {
  @ApiProperty()
  fileId: string;

  @ApiProperty()
  jobId: string;
}

export class BatchConvertResponseDto {
  @ApiProperty()
  batchId: string;

  @ApiProperty({ type: [BatchJobMappingDto] })
  jobs: BatchJobMappingDto[];
}

export class BatchFileStatusDto {
  @ApiProperty()
  jobId: string;

  @ApiProperty({ enum: ['pending', 'processing', 'completed', 'failed'] })
  status: string;

  @ApiProperty()
  progress: number;

  @ApiPropertyOptional()
  error?: string;
}

export class BatchStatusResponseDto {
  @ApiProperty()
  batchId: string;

  @ApiProperty({ enum: ['processing', 'completed', 'partial', 'failed'] })
  status: string;

  @ApiProperty()
  totalFiles: number;

  @ApiProperty()
  completedFiles: number;

  @ApiProperty({ type: [BatchFileStatusDto] })
  jobs: BatchFileStatusDto[];

  @ApiPropertyOptional()
  downloadUrl?: string;
}

export class BatchDownloadResponseDto {
  @ApiProperty()
  url: string;

  @ApiProperty()
  filename: string;

  @ApiProperty()
  expiresAt: string;
}

// Error DTOs
export class BatchErrorDto {
  @ApiProperty()
  error: string;

  @ApiProperty()
  message: string;
}
