// Interfaces para el sistema financiero del admin dashboard

// ============================================
// Exchange Rate (Tipo de cambio)
// ============================================

export interface ExchangeRate {
  id: string; // rate_YYYYMMDD
  date: string; // YYYY-MM-DD
  usdToMxn: number; // 1 USD = X MXN
  source: 'banxico' | 'fixer' | 'manual';
  fetchedAt: Date;
}

// ============================================
// Stripe Transactions (Transacciones)
// ============================================

export type TransactionType =
  | 'subscription'
  | 'upgrade'
  | 'renewal'
  | 'one_time'
  | 'refund'
  | 'chargeback';
export type TransactionStatus = 'succeeded' | 'failed' | 'refunded' | 'pending';

export interface StripeTransaction {
  id: string; // transaction_YYYYMMDD_XXXXX
  stripeEventId: string;
  stripeEventType: string;
  userId: string;
  userEmail: string;
  amount: number; // En centavos (como Stripe)
  currency: 'usd' | 'mxn';
  amountMxn: number; // Convertido a MXN para comparaciones
  exchangeRate: number; // Tipo de cambio usado
  type: TransactionType;
  plan: 'pro' | 'promax' | 'enterprise';
  stripeCustomerId: string;
  stripeSubscriptionId?: string;
  stripeInvoiceId?: string;
  stripePaymentIntentId?: string;
  status: TransactionStatus;
  billingCountry?: string; // País de facturación
  createdAt: Date;
  metadata?: Record<string, unknown>;
}

// ============================================
// Expenses (Gastos)
// ============================================

export type ExpenseType = 'recurring' | 'one_time';
export type ExpenseCategory = 'hosting' | 'advertising' | 'tools' | 'other';
export type RecurrenceType = 'monthly' | 'annual';

export interface Expense {
  id: string; // expense_YYYYMMDD_XXXXX
  amount: number;
  currency: 'usd' | 'mxn';
  amountMxn: number; // Siempre convertido a MXN
  exchangeRate: number; // Tipo de cambio usado
  type: ExpenseType;
  category: ExpenseCategory;
  description: string;
  vendor?: string; // Proveedor (AWS, Google, etc.)
  // Para gastos recurrentes
  recurrenceType?: RecurrenceType;
  nextGenerationDate?: Date; // Siguiente fecha de auto-generación
  parentExpenseId?: string; // ID del gasto recurrente padre (para auto-generados)
  // Metadata
  createdBy: string; // Admin email
  createdAt: Date;
  updatedAt?: Date;
  isAutoGenerated: boolean;
}

// ============================================
// Monthly Goals (Objetivos mensuales)
// ============================================

// Targets dinámicos - permite cualquier métrica
export type GoalTargets = Record<string, number>;

// Comportamiento de la métrica para cálculo de progreso
export type MetricBehavior = 'monthly' | 'cumulative' | 'point_in_time';

// Configuración de una métrica individual
export interface GoalMetricConfig {
  key: string; // e.g., 'revenue', 'traffic', 'cac'
  label: string;
  type: 'currency' | 'number' | 'percentage';
  icon: 'dollar' | 'users' | 'crown' | 'trending' | 'target' | 'chart' | 'ads' | 'conversion';
  color: 'green' | 'blue' | 'purple' | 'orange' | 'pink' | 'cyan' | 'amber' | 'red';
  currency?: 'USD' | 'MXN';
  order: number;
  behavior?: MetricBehavior; // Define cómo se calcula el progreso
}

// Métricas por defecto con behavior
export const DEFAULT_GOAL_METRICS: GoalMetricConfig[] = [
  { key: 'revenue', label: 'Ingresos', type: 'currency', icon: 'dollar', color: 'green', currency: 'USD', order: 1, behavior: 'monthly' },
  { key: 'newUsers', label: 'Usuarios Registrados', type: 'number', icon: 'users', color: 'blue', order: 2, behavior: 'cumulative' },
  { key: 'proConversions', label: 'Suscripciones Pro', type: 'number', icon: 'crown', color: 'purple', order: 3, behavior: 'cumulative' },
  { key: 'traffic', label: 'Tráfico', type: 'number', icon: 'trending', color: 'cyan', order: 4, behavior: 'monthly' },
  { key: 'conversionRate', label: 'Tasa de Conversión', type: 'percentage', icon: 'conversion', color: 'orange', order: 5, behavior: 'point_in_time' },
  { key: 'adsSpend', label: 'Inversión en Ads', type: 'currency', icon: 'ads', color: 'pink', currency: 'USD', order: 6, behavior: 'monthly' },
  { key: 'cac', label: 'CAC', type: 'currency', icon: 'target', color: 'amber', currency: 'USD', order: 7, behavior: 'monthly' },
  { key: 'profit', label: 'Utilidad Neta', type: 'currency', icon: 'chart', color: 'amber', currency: 'USD', order: 8, behavior: 'monthly' },
];

export interface GoalAlerts {
  [key: string]: boolean; // Dinámico: belowPace + metricKey
}

export interface MonthlyGoal {
  id: string; // goal_YYYYMM
  month: string; // YYYY-MM
  targets: GoalTargets;
  baseline?: GoalTargets; // Valores iniciales para métricas acumulativas
  actual?: GoalTargets; // Se actualiza automáticamente
  metrics?: GoalMetricConfig[]; // Configuración de métricas (usa defaults si no se especifica)
  alerts?: GoalAlerts; // Generadas por cron si vas por debajo
  createdBy: string;
  createdAt: Date;
  updatedAt?: Date;
}

// Historial de metas
export interface GoalHistoryItem {
  month: string;
  targets: GoalTargets;
  achieved: GoalTargets;
  metrics?: GoalMetricConfig[];
  status: 'on_track' | 'at_risk' | 'behind' | 'achieved';
}

// ============================================
// Subscription Events (Eventos de suscripción)
// ============================================

export type SubscriptionEventType =
  | 'started'
  | 'renewed'
  | 'canceled'
  | 'churned'
  | 'reactivated';

export interface SubscriptionEvent {
  id: string; // sub_event_YYYYMMDD_XXXXX
  userId: string;
  userEmail: string;
  eventType: SubscriptionEventType;
  plan: 'pro' | 'promax' | 'enterprise';
  previousPlan?: 'free' | 'pro' | 'promax' | 'enterprise';
  currency: 'usd' | 'mxn';
  mrr: number; // MRR en la moneda original
  mrrMxn: number; // MRR convertido a MXN
  stripeSubscriptionId: string;
  cancellationReason?: string;
  country?: string;
  createdAt: Date;
}

// ============================================
// Revenue Metrics (Métricas de ingresos)
// ============================================

export interface RevenueData {
  total: number;
  totalMxn: number;
  byCurrency: {
    usd: number;
    mxn: number;
  };
  mrr: number;
  mrrMxn: number;
  growth: number; // % vs período anterior
  transactionCount: number;
}

export interface MRRHistoryItem {
  month: string; // YYYY-MM
  mrr: number;
  mrrMxn: number;
  subscribers: number;
  churnedMrr: number;
  newMrr: number;
}

// ============================================
// Churn & LTV Metrics
// ============================================

export interface ChurnData {
  period: string;
  churnRate: number; // Porcentaje
  churnedUsers: number;
  totalSubscribers: number; // Total de suscriptores activos
  churnedMrr: number;
  churnedMrrMxn: number;
  trend: Array<{ month: string; churnRate: number }>;
}

export interface LTVData {
  avgLtv: number;
  avgLtvMxn: number;
  avgSubscriptionMonths: number;
  totalCustomers: number;
  avgMonthlyRevenue: number;
  byPlan: {
    pro: { ltv: number; avgMonths: number };
    promax: { ltv: number; avgMonths: number };
    enterprise: { ltv: number; avgMonths: number };
  };
}

// ============================================
// Profit Metrics
// ============================================

export interface ProfitData {
  period: string;
  revenue: number;
  revenueMxn: number;
  expenses: number;
  expensesMxn: number;
  profit: number;
  profitMxn: number;
  profitMargin: number; // Porcentaje
}
