// Interfaces para el sistema financiero del admin dashboard

// ============================================
// Exchange Rate (Tipo de cambio)
// ============================================

export interface ExchangeRate {
  id: string; // rate_YYYYMMDD
  date: string; // YYYY-MM-DD
  usdToMxn: number; // 1 USD = X MXN
  source: 'banxico' | 'fixer' | 'manual';
  fetchedAt: Date;
}

// ============================================
// Stripe Transactions (Transacciones)
// ============================================

export type TransactionType = 'subscription' | 'refund' | 'chargeback';
export type TransactionStatus = 'succeeded' | 'failed' | 'refunded' | 'pending';

export interface StripeTransaction {
  id: string; // transaction_YYYYMMDD_XXXXX
  stripeEventId: string;
  stripeEventType: string;
  userId: string;
  userEmail: string;
  amount: number; // En centavos (como Stripe)
  currency: 'usd' | 'mxn';
  amountMxn: number; // Convertido a MXN para comparaciones
  exchangeRate: number; // Tipo de cambio usado
  type: TransactionType;
  plan: 'pro' | 'enterprise';
  stripeCustomerId: string;
  stripeSubscriptionId?: string;
  stripeInvoiceId?: string;
  stripePaymentIntentId?: string;
  status: TransactionStatus;
  billingCountry?: string; // País de facturación
  createdAt: Date;
  metadata?: Record<string, unknown>;
}

// ============================================
// Expenses (Gastos)
// ============================================

export type ExpenseType = 'recurring' | 'one_time';
export type ExpenseCategory = 'hosting' | 'advertising' | 'tools' | 'other';
export type RecurrenceType = 'monthly' | 'annual';

export interface Expense {
  id: string; // expense_YYYYMMDD_XXXXX
  amount: number;
  currency: 'usd' | 'mxn';
  amountMxn: number; // Siempre convertido a MXN
  exchangeRate: number; // Tipo de cambio usado
  type: ExpenseType;
  category: ExpenseCategory;
  description: string;
  vendor?: string; // Proveedor (AWS, Google, etc.)
  // Para gastos recurrentes
  recurrenceType?: RecurrenceType;
  nextGenerationDate?: Date; // Siguiente fecha de auto-generación
  parentExpenseId?: string; // ID del gasto recurrente padre (para auto-generados)
  // Metadata
  createdBy: string; // Admin email
  createdAt: Date;
  updatedAt?: Date;
  isAutoGenerated: boolean;
}

// ============================================
// Monthly Goals (Objetivos mensuales)
// ============================================

export interface GoalTargets {
  revenue: number; // Ingreso objetivo en MXN
  newUsers: number; // Nuevos usuarios objetivo
  proConversions: number; // Conversiones Free->Pro objetivo
}

export interface GoalAlerts {
  belowPaceRevenue: boolean;
  belowPaceUsers: boolean;
  belowPaceConversions: boolean;
}

export interface MonthlyGoal {
  id: string; // goal_YYYYMM
  month: string; // YYYY-MM
  targets: GoalTargets;
  actual?: GoalTargets; // Se actualiza automáticamente
  alerts?: GoalAlerts; // Generadas por cron si vas por debajo
  createdBy: string;
  createdAt: Date;
  updatedAt?: Date;
}

// ============================================
// Subscription Events (Eventos de suscripción)
// ============================================

export type SubscriptionEventType =
  | 'started'
  | 'renewed'
  | 'canceled'
  | 'churned'
  | 'reactivated';

export interface SubscriptionEvent {
  id: string; // sub_event_YYYYMMDD_XXXXX
  userId: string;
  userEmail: string;
  eventType: SubscriptionEventType;
  plan: 'pro' | 'enterprise';
  previousPlan?: 'free' | 'pro' | 'enterprise';
  currency: 'usd' | 'mxn';
  mrr: number; // MRR en la moneda original
  mrrMxn: number; // MRR convertido a MXN
  stripeSubscriptionId: string;
  cancellationReason?: string;
  country?: string;
  createdAt: Date;
}

// ============================================
// Revenue Metrics (Métricas de ingresos)
// ============================================

export interface RevenueData {
  total: number;
  totalMxn: number;
  byCurrency: {
    usd: number;
    mxn: number;
  };
  mrr: number;
  mrrMxn: number;
  growth: number; // % vs período anterior
  transactionCount: number;
}

export interface MRRHistoryItem {
  month: string; // YYYY-MM
  mrr: number;
  mrrMxn: number;
  subscribers: number;
  churnedMrr: number;
  newMrr: number;
}

// ============================================
// Churn & LTV Metrics
// ============================================

export interface ChurnData {
  period: string;
  churnRate: number; // Porcentaje
  churnedUsers: number;
  totalSubscribers: number; // Total de suscriptores activos
  churnedMrr: number;
  churnedMrrMxn: number;
  trend: Array<{ month: string; churnRate: number }>;
}

export interface LTVData {
  avgLtv: number;
  avgLtvMxn: number;
  avgSubscriptionMonths: number;
  byPlan: {
    pro: { ltv: number; avgMonths: number };
    enterprise: { ltv: number; avgMonths: number };
  };
}

// ============================================
// Profit Metrics
// ============================================

export interface ProfitData {
  period: string;
  revenue: number;
  revenueMxn: number;
  expenses: number;
  expensesMxn: number;
  profit: number;
  profitMxn: number;
  profitMargin: number; // Porcentaje
}
