function _ts_decorate(decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for(var i = decorators.length - 1; i >= 0; i--)if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
}
function _ts_metadata(k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
}
import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { IsString, IsArray, IsNotEmpty, ValidateNested, ArrayMinSize, IsEnum, IsOptional } from "class-validator";
import { Type } from "class-transformer";
// Input DTOs
export class BatchFileDto {
}
_ts_decorate([
    ApiProperty({
        description: 'UUID generated by frontend'
    }),
    IsString(),
    IsNotEmpty(),
    _ts_metadata("design:type", String)
], BatchFileDto.prototype, "id", void 0);
_ts_decorate([
    ApiProperty({
        description: 'ZPL content'
    }),
    IsString(),
    IsNotEmpty(),
    _ts_metadata("design:type", String)
], BatchFileDto.prototype, "content", void 0);
_ts_decorate([
    ApiProperty({
        description: 'Original file name'
    }),
    IsString(),
    IsNotEmpty(),
    _ts_metadata("design:type", String)
], BatchFileDto.prototype, "fileName", void 0);
export class BatchConvertDto {
}
_ts_decorate([
    ApiProperty({
        type: [
            BatchFileDto
        ],
        description: 'Array of ZPL files to convert'
    }),
    IsArray(),
    ArrayMinSize(1),
    ValidateNested({
        each: true
    }),
    Type(()=>BatchFileDto),
    _ts_metadata("design:type", Array)
], BatchConvertDto.prototype, "files", void 0);
_ts_decorate([
    ApiProperty({
        description: 'Label size (e.g., 4x6, 4x4)'
    }),
    IsString(),
    IsNotEmpty(),
    _ts_metadata("design:type", String)
], BatchConvertDto.prototype, "labelSize", void 0);
_ts_decorate([
    ApiPropertyOptional({
        enum: [
            'pdf',
            'png',
            'jpeg'
        ],
        default: 'pdf'
    }),
    IsOptional(),
    IsEnum([
        'pdf',
        'png',
        'jpeg'
    ]),
    _ts_metadata("design:type", String)
], BatchConvertDto.prototype, "outputFormat", void 0);
// Response DTOs
export class BatchJobMappingDto {
}
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchJobMappingDto.prototype, "fileId", void 0);
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchJobMappingDto.prototype, "jobId", void 0);
export class BatchConvertResponseDto {
}
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchConvertResponseDto.prototype, "batchId", void 0);
_ts_decorate([
    ApiProperty({
        type: [
            BatchJobMappingDto
        ]
    }),
    _ts_metadata("design:type", Array)
], BatchConvertResponseDto.prototype, "jobs", void 0);
export class BatchFileStatusDto {
}
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchFileStatusDto.prototype, "jobId", void 0);
_ts_decorate([
    ApiProperty({
        enum: [
            'pending',
            'processing',
            'completed',
            'failed'
        ]
    }),
    _ts_metadata("design:type", String)
], BatchFileStatusDto.prototype, "status", void 0);
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", Number)
], BatchFileStatusDto.prototype, "progress", void 0);
_ts_decorate([
    ApiPropertyOptional(),
    _ts_metadata("design:type", String)
], BatchFileStatusDto.prototype, "error", void 0);
export class BatchStatusResponseDto {
}
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchStatusResponseDto.prototype, "batchId", void 0);
_ts_decorate([
    ApiProperty({
        enum: [
            'processing',
            'completed',
            'partial',
            'failed'
        ]
    }),
    _ts_metadata("design:type", String)
], BatchStatusResponseDto.prototype, "status", void 0);
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", Number)
], BatchStatusResponseDto.prototype, "totalFiles", void 0);
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", Number)
], BatchStatusResponseDto.prototype, "completedFiles", void 0);
_ts_decorate([
    ApiProperty({
        type: [
            BatchFileStatusDto
        ]
    }),
    _ts_metadata("design:type", Array)
], BatchStatusResponseDto.prototype, "jobs", void 0);
_ts_decorate([
    ApiPropertyOptional(),
    _ts_metadata("design:type", String)
], BatchStatusResponseDto.prototype, "downloadUrl", void 0);
export class BatchDownloadResponseDto {
}
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchDownloadResponseDto.prototype, "url", void 0);
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchDownloadResponseDto.prototype, "filename", void 0);
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchDownloadResponseDto.prototype, "expiresAt", void 0);
// Error DTOs
export class BatchErrorDto {
}
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchErrorDto.prototype, "error", void 0);
_ts_decorate([
    ApiProperty(),
    _ts_metadata("design:type", String)
], BatchErrorDto.prototype, "message", void 0);

//# sourceMappingURL=batch.dto.js.map